configfilepath: /Users/kaanyagci/Documents/makepad/qonto4j/.concom.yml
path: ""
version: 0.0.1
scopes:
    - name: config
      description: All changes on the configuration files
    - name: tests
      description: All changes on the tests
    - name: qonto
      description: All changes on the Qonto core class
    - name: transfers
      description: All changes related to the transfers endpoint
    - name: external-trasfers
      description: All changes related external transfers endpoint
    - name: internal-transfers
      description: All changes related internal transfers endpoint
    - name: attachments
      description: All changes related attachments endpoint
    - name: transactions-attachments
      description: All changes related to the transaction's attachments endpoint
    - name: beneficiaires
      description: All changes related beneficiaires endpoint
    - name: labels
      description: All changes related labels endpoint
    - name: memberships
      description: All changes related memberships endpoint
    - name: oranizations
      description: All changes related organizations endpoint
    - name: requests
      description: All changes related requests endpoint
    - name: transactions
      description: All changes related transactions endpoint
    - name: wrapper
      description: All changes related to the API wrapper aka HTTPHandler
conventions:
    - name: build
      description: Changes that affect the build system or external dependencies
    - name: ci
      description: Changes to our CI configuration files and scripts
    - name: docs
      description: Documentation only changes
    - name: feat
      description: A new feature
    - name: revert
      description: 'If the commit reverts a previous commit, it should begin with revert: , followed by the header of the reverted commit. In the body it should say: This reverts commit <hash>., where the hash is the SHA of the commit being reverted.'
    - name: fix
      description: A bug fix
    - name: perf
      description: A code change that improves performance
    - name: refactor
      description: A code change that neither fixes a bug nor adds a feature
    - name: style
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - name: test
      description: Adding missing tests or correcting existing tests
